### ISSUE TITLE
Preprocess DSD100 dataset for SVSGan

### ISSUE THREAD

**Issue by q-hwang** [CornellDataScience/IntSys-Vocal-Isolation#3]
Prepare the whole dataset for SVSGan pertaining; should support different split ratio

**Comment by Xiuyu-Li** [comment]
The loading of the whole dataset works correctly but is extremely slow; will try to figure out a way to fix it and implement support for redistributing training and testing files with arbitrary rations.

**Comment by q-hwang** [comment]
We change to use MUSDB to compare with Wave-U-Net. Should try to process MUSDB in gcloud machine and run train.py over it.

**Comment by q-hwang** [comment]
Also we want to use log scale magnitude spectrogram in training

**Comment by q-hwang** [comment]
Done loading
