### ISSUE TITLE
Dataset converting

### ISSUE THREAD

**Issue by q-hwang** [CornellDataScience/IntSys-Vocal-Isolation#8]
Use MUSDB dataset. Convert the whole dataset to mono and downsample 16000.

**Comment by yuzhshen** [comment]
Done, WAV files saved to same directory as MUSDB MP4, e.g. `Wave-U-Net/data/musdb/train/`.

**Comment by yuzhshen** [comment]
Done, WAV files saved to same directory as MUSDB MP4, e.g. `Wave-U-Net/data/musdb/train/`.
